default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twitter_clone_dev
  host: "localhost"
  username: "twitter_clone"
  password: "000000"

test:
  <<: *default
  database: twitter_clone_test

production:
  <<: *default
  database: twitter_clone_production
  username: twitter_clone
  password: <%= ENV['TWITTER_CLONE_DATABASE_PASSWORD'] %>
